import { CHIBI_SCALES } from '../../../services/chibiScaling';

export const STANDARD_3D_SCALES = {
  TILE_UNIT_SIZE: CHIBI_SCALES.TILE_UNIT_SIZE,
  CHARACTER_HEIGHT: CHIBI_SCALES.CHARACTER_HEIGHT, 
  CHARACTER_WIDTH: CHIBI_SCALES.CHARACTER_WIDTH,   
  PREY_HEIGHT: CHIBI_SCALES.PREY_HEIGHT,
  PREY_WIDTH: CHIBI_SCALES.PREY_WIDTH,
  PROP_CHEST_HEIGHT: CHIBI_SCALES.PROP_CHEST_HEIGHT,
  PROP_DECORATION_HEIGHT: CHIBI_SCALES.PROP_DECORATION_HEIGHT,
  FLOOR_Y_OFFSET: CHIBI_SCALES.FLOOR_Y_OFFSET,
  SHADOW_SCALE: CHIBI_SCALES.SHADOW_SCALE,
} as const;
